spring.application.name=product

# Configure PostgresSQL Database
spring.datasource.url=jdbc:postgresql:://localhost:5432/inventory_management_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


